name: Auto Post to FB

on:
  schedule:
    - cron: '*/20 * * * *'  # প্রতি 20 মিনিটে চালাবে
  workflow_dispatch:       # ম্যানুয়ালি চালানোর জন্য

jobs:
  post_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          PAGE_URL: ${{ secrets.PAGE_URL }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Commit posted_articles.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_articles.json
          git commit -m "Update posted_articles.json [skip ci]" || echo "No changes to commit"
          git push
