name: Auto Post to FB

on:
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টা চালাবে
  workflow_dispatch:

jobs:
  post_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "lxml[html_clean]"  # newspaper এর জন্য প্রয়োজন
          pip install lxml_html_clean      # fallback

      - name: Run Script
        env:
          PAGE_URL: ${{ secrets.PAGE_URL }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
